### ISSUE TITLE
Feature request: verbs

### ISSUE THREAD

**Issue by zfedoran** [code-payments/code-sdk#9]
A number of community members have requested additional verbs on the `Pay with Code` button.

It would be helpful to get feedback on what types of verbs people are requesting.

Looking at [Apple](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaybuttontype), [Google](https://developers.google.com/pay/api/web/guides/resources/customize), and [Stripe](https://stripe.com/docs/stripe-js/elements/payment-request-button) button implementations, the verbs offered are limited to at most the following (with Apple having the largest set):

- "add-money"
- "book"
- "buy"
- "check-out"
- "continue"
- "contribute"
- "donate"
- "order"
- "pay"
- "plain"
- "reload"
- "rent"
- "set-up"
- "subscribe"
- "support"
- "tip"
- "top-up"

**Comment by metasal1** [comment]
Our product is playing on the “Insert Kin” theme for our upcoming app.

Our suggestion would be to allow any term and grow or shrink the button with min and max width

**Comment by zfedoran** [comment]
This feature will be implemented once the login work lands. The login feature is helping define how different "modes" might be implemented.

**Comment by zfedoran** [comment]
Closing this for now as we actively adding more verbs and this is much larger item than just a button name change. In order to provide the best possible UX, the mobile apps have special treatment for each of these. Current list includes payment, login, and tips.
